pipeline{
	agent any
	
	tools{
		maven 'maven-3.9.6'
	}
	
	stages{
		
		stage('build jar') {
			steps{
				dir('docker-jenkins-demo') {
					bat 'mvn clean install'
				}
			}
		}
		
		stage('build docker image') {
			steps{
				dir('docker-jenkins-demo') {
				bat 'docker build -t saikumar1605/docker-jenkins-integration .'
			}
		}
		
		stage('push image to hub') {
			steps{
				dir('docker-jenkins-demo') {
					withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]){
						bat 'docker login -u saikumar1605 -p %dockerhubpwd%'
					}
					bat 'docker push saikumar1605/docker-jenkins-integration'
				}
			}
		}
		
		stage('run container') {
			steps{
				dir('docker-jenkins-demo') {
					bat 'docker run -d -p 9090:8085 --name jenkins-docker-container saikumar1605/docker-jenkins-integration'
				}
			}
		}
	}
}