pipeline{
	agent any
	
	tools{
		maven 'maven-3.9.6'
	}
	
	stages{
		stage('build jar') {
			steps {
				dir('docker-jenkins-demo') {
					bat 'mvn clean package'
				}
			}
		}
		
		stage('build docker image') {
			steps{
				dir('docker-jenkins-demo') {
					bat 'docker build -t saikumar1605/docker-jenkins .'
				}
			}
		}
		
		stage('push image to hub') {
			steps{
				dir('docker-integration-demo') {
					withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
						bat 'docker login -u saikumar1605 -p %dockerhubpwd%'
					}
					
					bat 'docker push saikumar1605/docker-jenkins'
				}
			}
		}
		
		stage('run container') {
			steps{
				dir('docker-integration-demo') {
					bat 'docker run -d -p 8085:8085 --name docker-jenkins-container saikumar1605/docker-jenkins'
				}
			}
		}
	}
}