pipeline {
    agent any

    tools {
        maven 'maven-3.9.6'
    }

    stages {
        stage('Build JAR') {
            steps {
                dir('docker-integration-api') {
                    bat 'mvn clean install'
                }
            } 
        }
        
        stage('Build Docker Image'){
			steps{
				dir('docker-integration-api') {
                    bat 'docker build -t saikumar1605/docker-jenkins-integration .'
				}
			}
		}
		stage('Push image to Hub') {
            steps {
                dir('docker-integration-api') {
                    withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                        bat 'docker login -u saikumar1605 -p %dockerhubpwd%'
                    }
                    bat 'docker push saikumar1605/docker-jenkins-integration'
                }
            }
        }
    }
}