pipeline {
    agent any

    tools {
        maven 'maven-3.9.6'
    }

    stages {
        stage('Build JAR') {
            steps {
                dir('docker-integration-api') {
                    bat 'mvn clean install'
                }
            }
        }
    }
}