pipeline {
    agent any

    tools {
        maven 'maven-3.9.6'
    }

    stages {
        stage('Build JAR') {
            steps {
                bat 'mvn clean install'
            }
        }
    }
}